export const grammarQuestions = [
  // Present Simple / Continuous / Perfect
  { id: "g1", category: "Present Tenses", question: "She ____ to school every day.", options: ["go", "going", "went", "goes"], answer: 3 },
  { id: "g2", category: "Present Tenses", question: "They ____ football now.", options: ["plays", "are playing", "played", "play"], answer: 1 },
  { id: "g3", category: "Present Tenses", question: "I ____ already finished my homework.", options: ["am", "was", "have", "had"], answer: 2 },
  { id: "g4", category: "Present Tenses", question: "He ____ not like coffee.", options: ["do", "does", "did", "doing"], answer: 1 },
  { id: "g5", category: "Present Tenses", question: "We ____ studying for the exam at the moment.", options: ["study", "studied", "are", "are studying"], answer: 3 },
  { id: "g6", category: "Present Tenses", question: "She ____ lived here since 2020.", options: ["is", "has", "was", "have"], answer: 1 },
  { id: "g7", category: "Present Tenses", question: "They ____ dinner every night at 8.", options: ["eating", "eat", "eats", "ate"], answer: 1 },
  { id: "g8", category: "Present Tenses", question: "I ____ working on the project now.", options: ["was", "am", "is", "be"], answer: 1 },
  // Past
  { id: "g9", category: "Past Tenses", question: "He ____ to Cairo yesterday.", options: ["go", "going", "gone", "went"], answer: 3 },
  { id: "g10", category: "Past Tenses", question: "They ____ when I called them.", options: ["sleep", "were sleeping", "slept", "are sleeping"], answer: 1 },
  { id: "g11", category: "Past Tenses", question: "She ____ a letter last night.", options: ["writes", "writing", "wrote", "written"], answer: 2 },
  { id: "g12", category: "Past Tenses", question: "I ____ TV when the lights went out.", options: ["watch", "was watching", "watched", "watching"], answer: 1 },
  { id: "g13", category: "Past Tenses", question: "We ____ the match yesterday.", options: ["win", "winning", "won", "wins"], answer: 2 },
  { id: "g14", category: "Past Tenses", question: "He ____ working when I arrived.", options: ["is", "was", "were", "be"], answer: 1 },
  // Prepositions
  { id: "g15", category: "Prepositions", question: "The book is ____ the table.", options: ["on", "in", "at", "under"], answer: 0 },
  { id: "g16", category: "Prepositions", question: "She is good ____ math.", options: ["on", "at", "in", "for"], answer: 1 },
  { id: "g17", category: "Prepositions", question: "We arrived ____ school early.", options: ["in", "at", "on", "to"], answer: 1 },
  { id: "g18", category: "Prepositions", question: "He lives ____ Cairo.", options: ["on", "in", "at", "by"], answer: 1 },
  { id: "g19", category: "Prepositions", question: "The meeting is ____ Monday.", options: ["in", "at", "on", "by"], answer: 2 },
  // Adjectives/Adverbs
  { id: "g20", category: "Adjectives & Adverbs", question: "She is a ____ student.", options: ["quickly", "quick", "quicker", "quickness"], answer: 1 },
  { id: "g21", category: "Adjectives & Adverbs", question: "He runs ____ in the race.", options: ["fast", "faster", "fastest", "fastly"], answer: 0 },
  { id: "g22", category: "Adjectives & Adverbs", question: "This is the ____ book I have read.", options: ["good", "better", "best", "well"], answer: 2 },
  { id: "g23", category: "Adjectives & Adverbs", question: "They speak English ____.", options: ["good", "best", "better", "well"], answer: 3 },
  { id: "g24", category: "Adjectives & Adverbs", question: "It is a ____ day today.", options: ["beautifully", "beautiful", "beauty", "beautify"], answer: 1 },
  // Word Order
  { id: "g25", category: "Word Order", question: "____ is my friend Ahmed.", options: ["This", "He", "They", "We"], answer: 0 },
  { id: "g26", category: "Word Order", question: "She ____ a new car.", options: ["have", "having", "has", "had"], answer: 2 },
  { id: "g27", category: "Word Order", question: "I ____ my homework yesterday.", options: ["do", "doing", "did", "does"], answer: 2 },
  { id: "g28", category: "Word Order", question: "They ____ to school every day.", options: ["go", "going", "gone", "goes"], answer: 0 },
  { id: "g29", category: "Word Order", question: "____ you like tea?", options: ["Are", "Do", "Does", "Did"], answer: 1 },
  // Clauses
  { id: "g30", category: "Clauses", question: "I stayed home ____ I was sick.", options: ["but", "because", "and", "or"], answer: 1 },
  { id: "g31", category: "Clauses", question: "This is the place ____ I was born.", options: ["what", "where", "when", "who"], answer: 1 },
  { id: "g32", category: "Clauses", question: "He didn't come ____ he was busy.", options: ["so", "because", "but", "and"], answer: 1 },
  { id: "g33", category: "Clauses", question: "I know the man ____ helped us.", options: ["where", "who", "when", "which"], answer: 1 },
  { id: "g34", category: "Clauses", question: "She went home ____ she finished work.", options: ["but", "and", "after", "or"], answer: 2 },
  // Mixed
  { id: "g35", category: "Mixed Grammar", question: "There ____ many students in the class.", options: ["is", "was", "are", "be"], answer: 2 },
  { id: "g36", category: "Mixed Grammar", question: "I have ____ finished my project.", options: ["yet", "ever", "already", "still"], answer: 2 },
  { id: "g37", category: "Mixed Grammar", question: "He ____ to music every evening.", options: ["listen", "listens", "listening", "listened"], answer: 1 },
  { id: "g38", category: "Mixed Grammar", question: "We ____ playing football now.", options: ["is", "are", "am", "be"], answer: 1 },
  { id: "g39", category: "Mixed Grammar", question: "She ____ not come yesterday.", options: ["do", "does", "did", "doing"], answer: 2 },
  { id: "g40", category: "Mixed Grammar", question: "They have lived here ____ five years.", options: ["for", "since", "in", "at"], answer: 0 },
  // Advanced
  { id: "g41", category: "Advanced Mix", question: "I ____ seen that movie before.", options: ["is", "was", "have", "had"], answer: 2 },
  { id: "g42", category: "Advanced Mix", question: "He was reading when I ____.", options: ["come", "came", "comes", "coming"], answer: 1 },
  { id: "g43", category: "Advanced Mix", question: "She ____ English very well.", options: ["speak", "speaks", "speaking", "spoke"], answer: 1 },
  { id: "g44", category: "Advanced Mix", question: "The train ____ at 6 pm yesterday.", options: ["arrive", "arriving", "arrived", "arrives"], answer: 2 },
  { id: "g45", category: "Advanced Mix", question: "They ____ dinner now.", options: ["eat", "ate", "are eating", "eating"], answer: 2 },
  // Final
  { id: "g46", category: "Final Mix", question: "He is the boy ____ helped me.", options: ["when", "where", "who", "which"], answer: 2 },
  { id: "g47", category: "Final Mix", question: "I ____ never been to London.", options: ["is", "was", "have", "had"], answer: 2 },
  { id: "g48", category: "Final Mix", question: "She ____ watching TV at 8 pm.", options: ["is", "was", "were", "be"], answer: 1 },
  { id: "g49", category: "Final Mix", question: "We ____ finished our work.", options: ["has", "had", "have", "having"], answer: 2 },
  { id: "g50", category: "Final Mix", question: "They ____ to school every day.", options: ["go", "went", "going", "goes"], answer: 0 },
];

export const itCards = [
  { id: "it1", term: "Internet", definition: "A global network of interconnected computers that allows sharing of information and communication worldwide." },
  { id: "it2", term: "Web browser", definition: "Software used to access and view content on the internet (e.g. Chrome, Firefox, Safari)." },
  { id: "it3", term: "Database", definition: "An organised collection of structured data stored electronically, managed by a Database Management System (DBMS)." },
  { id: "it4", term: "Algorithm", definition: "A step-by-step set of instructions or rules designed to solve a problem or complete a task." },
  { id: "it5", term: "Table", definition: "A database object that stores data in rows (records) and columns (fields), similar to a spreadsheet." },
  { id: "it6", term: "IP address", definition: "A unique numerical label assigned to each device on a network, used to identify and communicate with it." },
  { id: "it7", term: "Switch", definition: "A networking device that connects multiple devices within a LAN and forwards data to the correct destination." },
  { id: "it8", term: "Router", definition: "A device that forwards data packets between different networks, directing internet traffic to the correct destination." },
  { id: "it9", term: "Virus", definition: "A type of malicious software that attaches itself to files and spreads to other computers, often causing damage." },
  { id: "it10", term: "Firewall", definition: "A security system that monitors and controls incoming and outgoing network traffic based on predefined security rules." },
  { id: "it11", term: "Compiler", definition: "A program that translates high-level source code written by a programmer into machine code that a computer can execute." },
  { id: "it12", term: "Operating system", definition: "System software that manages computer hardware and software resources and provides services for programs (e.g. Windows, macOS)." },
  { id: "it13", term: "Application software", definition: "Programs designed to perform specific tasks for users, such as word processors, browsers, or games." },
  { id: "it14", term: "Encryption", definition: "The process of converting data into a coded form (ciphertext) to prevent unauthorised access." },
  { id: "it15", term: "Decryption", definition: "The process of converting encrypted data back into its original readable form using a key." },
  { id: "it16", term: "Hard disk", definition: "A storage device that uses magnetic platters to store data permanently inside or outside a computer." },
  { id: "it17", term: "RAM", definition: "Random Access Memory — temporary, fast memory used by a computer to store data that is actively being used or processed." },
  { id: "it18", term: "ROM", definition: "Read Only Memory — permanent memory that stores data which cannot normally be modified, used to store firmware." },
  { id: "it19", term: "Network", definition: "A group of two or more computers or devices connected together to share resources and communicate." },
  { id: "it20", term: "Keyboard", definition: "An input device with keys used to enter text, numbers, and commands into a computer." },
  { id: "it21", term: "Mouse", definition: "An input device used to control a pointer on screen and interact with graphical user interfaces." },
  { id: "it22", term: "Chart", definition: "A visual representation of data, such as a bar chart, pie chart, or line graph, used to show patterns and comparisons." },
  { id: "it23", term: "Protocol", definition: "A set of rules that governs how data is transmitted and received over a network (e.g. HTTP, TCP/IP, FTP)." },
  { id: "it24", term: "Homepage", definition: "The main or introductory page of a website, usually the first page a visitor sees." },
  { id: "it25", term: "Word processor", definition: "Software used to create, edit, format, and print text documents (e.g. Microsoft Word, Google Docs)." },
  { id: "it26", term: "Worm", definition: "A type of malware that replicates itself and spreads across networks without needing to attach to a host file." },
  { id: "it27", term: "Cloud computing", definition: "Delivering computing services such as storage, processing power, and software over the internet on demand." },
  { id: "it28", term: "Website", definition: "A collection of related web pages hosted on a server, accessible via the internet through a web browser." },
  { id: "it29", term: "Backup", definition: "A copy of data saved separately so it can be restored if the original is lost, corrupted, or accidentally deleted." },
  { id: "it30", term: "Bug", definition: "An error or flaw in a program's code that causes it to behave unexpectedly or produce incorrect results." },
  { id: "it31", term: "Modem", definition: "A device that modulates and demodulates signals to connect a computer to the internet via a telephone or cable line." },
  { id: "it32", term: "SDLC", definition: "Software Development Life Cycle — a structured process for planning, creating, testing, and deploying software systems." },
  { id: "it33", term: "SQL", definition: "Structured Query Language — a programming language used to create, manage, and query relational databases." },
  { id: "it34", term: "Normalization", definition: "The process of organising a database to reduce data redundancy and improve data integrity by dividing data into related tables." },
  { id: "it35", term: "LAN", definition: "Local Area Network — a network connecting devices within a limited area such as a home, office, or campus building." },
  { id: "it36", term: "WAN", definition: "Wide Area Network — a network that spans large geographical areas, connecting multiple LANs (e.g. the internet)." },
  { id: "it37", term: "Intrusion Detection System", definition: "Software or hardware that monitors network traffic for suspicious activity and alerts administrators to potential threats." },
  { id: "it38", term: "Authentication", definition: "The process of verifying the identity of a user or device before granting access to a system or resource." },
  { id: "it39", term: "Authorization", definition: "The process of determining what resources or actions an authenticated user is permitted to access or perform." },
  { id: "it40", term: "Digital signature", definition: "An electronic verification method that authenticates the identity of the sender and ensures a message has not been altered." },
  { id: "it41", term: "Presentation software", definition: "Software used to create slideshows and visual presentations (e.g. Microsoft PowerPoint, Google Slides)." },
  { id: "it42", term: "Big data", definition: "Extremely large and complex datasets that cannot be processed by traditional software tools and require specialised analytics." },
  { id: "it43", term: "Artificial Intelligence", definition: "The simulation of human intelligence in machines, enabling them to perform tasks like learning, reasoning, and problem-solving." },
  { id: "it44", term: "Cache memory", definition: "A small, fast memory storage located close to the CPU that stores frequently accessed data for quicker retrieval." },
  { id: "it45", term: "Cloud storage", definition: "A service that stores data on remote servers accessed via the internet, rather than on local physical devices." },
  { id: "it46", term: "DDoS", definition: "Distributed Denial of Service — a cyberattack that overwhelms a server with traffic from many sources, making it unavailable." },
  { id: "it47", term: "Debugging", definition: "The process of identifying, analysing, and fixing errors (bugs) in a program's source code." },
  { id: "it48", term: "HTML", definition: "HyperText Markup Language — the standard language used to create and structure content on web pages." },
  { id: "it49", term: "Version control system", definition: "A system that tracks and manages changes to source code over time, enabling collaboration and rollback (e.g. Git)." },
  { id: "it50", term: "Data fragmentation", definition: "The condition where data is stored non-contiguously across a storage device, leading to reduced performance and wasted space." },
];
